insert into topics (name, description, created_at, updated_at)
values ('Programming',
        'Software development and coding fundamentals',
        now(),
        now()),
    ('Web Development',
     'Building modern web applications',
     now(),
     now()),
    ('Data Science',
     'Data analysis, statistics, and visualization',
     now(),
     now()),
    ('Machine Learning',
     'Algorithms that learn from data',
     now(),
     now()),
    ('Databases',
     'Relational and non-relational data storage',
     now(),
     now()),
    ('DevOps',
     'CI/CD, containers, and infrastructure automation',
     now(),
     now()),
    ('Cybersecurity',
     'Securing systems, networks, and applications',
     now(),
     now()),
    ('Cloud Computing',
     'Cloud platforms and distributed systems',
     now(),
     now()),
    ('Mobile Development',
     'Building apps for iOS and Android',
     now(),
     now()),
    ('UI/UX Design',
     'Designing usable and accessible interfaces',
     now(),
     now());

insert into courses (title, description, price, capacity, start_date, end_date, topic_id, created_at, updated_at)
values ('Introduction to Java',
        'Learn the basics of Java programming',
        49.99,
        50,
        '2026-06-01',
        '2026-08-01',
        (select id from topics where name = 'Programming'),
        now(),
        now()),
    ('Full-Stack with Spring Boot',
     'Build REST APIs and web apps with Spring Boot',
     89.99,
     40,
     '2026-06-15',
     '2026-09-15',
     (select id from topics where name = 'Web Development'),
     now(),
     now()),
    ('Data Analysis with Python',
     'Analyze data using pandas and NumPy',
     69.99,
     60,
     '2026-07-01',
     '2026-09-01',
     (select id from topics where name = 'Data Science'),
     now(),
     now()),
    ('Machine Learning Fundamentals',
     'Supervised and unsupervised learning basics',
     99.99,
     35,
     '2026-07-10',
     '2026-10-10',
     (select id from topics where name = 'Machine Learning'),
     now(),
     now()),
    ('SQL Mastery',
     'Master querying and designing relational databases',
     59.99,
     70,
     '2026-06-05',
     '2026-08-05',
     (select id from topics where name = 'Databases'),
     now(),
     now()),
    ('Docker and Kubernetes',
     'Containerize and orchestrate applications',
     79.99,
     45,
     '2026-08-01',
     '2026-10-01',
     (select id from topics where name = 'DevOps'),
     now(),
     now()),
    ('Ethical Hacking Basics',
     'Penetration testing and security fundamentals',
     109.99,
     30,
     '2026-07-20',
     '2026-10-20',
     (select id from topics where name = 'Cybersecurity'),
     now(),
     now()),
    ('AWS for Beginners',
     'Get started with Amazon Web Services',
     84.99,
     55,
     '2026-06-20',
     '2026-09-20',
     (select id from topics where name = 'Cloud Computing'),
     now(),
     now()),
    ('Android App Development',
     'Build native Android apps with Kotlin',
     74.99,
     40,
     '2026-08-10',
     '2026-11-10',
     (select id from topics where name = 'Mobile Development'),
     now(),
     now()),
    ('UX Design Principles',
     'Create intuitive and accessible user experiences',
     64.99,
     50,
     '2026-07-05',
     '2026-09-05',
     (select id from topics where name = 'UI/UX Design'),
     now(),
     now());