insert into enrollments (course_id, user_id, created_at, updated_at)
values ((select id from courses where title = 'Introduction to Java'),
        (select id from users where username = 'student1'),
        now(),
        now()),
    ((select id from courses where title = 'Full-Stack with Spring Boot'),
     (select id from users where username = 'student1'),
     now(),
     now()),
    ((select id from courses where title = 'Data Analysis with Python'),
     (select id from users where username = 'student1'),
     now(),
     now()),
    ((select id from courses where title = 'Introduction to Java'),
     (select id from users where username = 'student2'),
     now(),
     now()),
    ((select id from courses where title = 'SQL Mastery'),
     (select id from users where username = 'student2'),
     now(),
     now()),
    ((select id from courses where title = 'Docker and Kubernetes'),
     (select id from users where username = 'student2'),
     now(),
     now()),
    ((select id from courses where title = 'Machine Learning Fundamentals'),
     (select id from users where username = 'student3'),
     now(),
     now()),
    ((select id from courses where title = 'AWS for Beginners'),
     (select id from users where username = 'student3'),
     now(),
     now()),
    ((select id from courses where title = 'Android App Development'),
     (select id from users where username = 'student3'),
     now(),
     now()),
    ((select id from courses where title = 'UX Design Principles'),
     (select id from users where username = 'student3'),
     now(),
     now());